use_frameworks!

inhibit_all_warnings!

target 'PreneticsTestCocoa_Example' do
  pod 'Intercom', '~> 3.2.5'
  pod 'PreneticsTestCocoa', :path => '../'

  target 'PreneticsTestCocoa_Tests' do
    inherit! :search_paths

    
  end
end
